# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BRANDSTORE.TIROL
email: socialmedia@brandstore.tirol
description: >- # this means to ignore newlines until "baseurl:"
          Bevor es losgeht, möchten wir euch mitteilen, warum wir dieses Projekt ins Leben gerufen haben, was unsere Motivation und Vision dahinter ist und welches Ziel wir uns gesetzt haben.
          Aus Liebe zur Natur und zum Sport <b>(&#35;love)</b> entwickelte sich die Leidenschaft (&#35;passion)zur Marke und den Produkten, die Begeisterung (&#35;enthusiasm) für das Team und die Vision dahinter, 
          der Traum (&#35;dream), ein Teil davon zu werden und letztendlich das Projekt (&#35;project), all das in die Realität umzusetzen.
          Daraus entstand der Wunsch, unseren Kunden die Möglichkeit zu bieten, Teil dieser Geschichte zu werden, sie mitzuschreiben und zu erleben.
          Wir möchten uns beim Team der Martini Sportswear GmbH (&#35;martinisportswear &#35;designyoursports) für diese wunderbare Inspiration und die Möglichkeit, uns verwirklichen zu können, aus tiefstem Herzen bedanken und freuen uns
          auf eine langjährige und intensive Zusammenarbeit.
          Wir leben und teilen die Tradition und Philosophie unserer Brands und werden alles versuchen, in der heutigen Zeit von Rücksichtslosigkeit, Respektlosigkeit, Schnelllebigkeit und Ignoranz, 
          Shopping wieder zu einem Wohlfühlerlebnis zu machen (&#35;aufaguadezeit)
          BRANDSTORE.TIROL (&#35;brandstoretirol)... eine Geschichte wird Programm (&#35;lebdeilebn)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
port: 4001

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
collections:
    news:
        output: true
